---
title: "Resume"
format:
  html:
    toc: true
  pdf:
    author: Nicholas Marino
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
nac.marino@gmail.com
:::

## EDUCATION

**Doctor of Philosophy -- Econometrics and Business Statistics** <br> *Monash University* [*Aug 2021 --- Present*]{.cvdate}

-   New principles and methods for complex data preparation and integration, with applications to official statistics, web-scrapped data and satellite raster images
-   Monash Data Futures Institute PhD Top-Up Scholarship (2021-2024)
-   Expected submission date: Nov 2024

## WORK EXPERIENCE{style="page-break-before: always"}

### Data Scientist

***Freelance, Multiple Clients*** [Jan 2020 -- June 2021]{.cvdate}

Providing data collection, pre-processing, exploratory analysis and modelling services to clients in the early R&D stages of developing data driven products. Projects include:

-   Data description and preliminary product feasibility insights for a start-up real estate bond platform; including assessing suitability of various property transaction databases for use in initial product prototype.
-   Development of statistical anomaly detection regimes and key historical insights from internet quality time-series data for use in parametric insurance products, including documenting analysis tools in an R package.

::: {.no-print}
## PRESENTATIONS AND WORKSHOPS

-   Talk: [Misadventures with Reproducibility in R](https://github.com/cynthiahqy/rladies-2022-11) (30 Nov 2022, R Ladies Melbourne Meetup)
-   Talk: [Designing R Packages](https://github.com/cynthiahqy/design-r-magic_2022-10) (4 Oct 2022, Monash EBS Data Science Research Software Study Group)
-   Talk: [Quarto Websites as Research Compendiums](https://github.com/cynthiahqy/quarto-wiki-template) (16 Aug 2022, Monash EBS Data Science Research Software Study Group)
-   Workshop: [Writing academic papers with Rmarkdown and friends](https://www.cynthiahqy.com/posts/r-markdown-and-friends/) (9 Aug 2022, Monash University)
:::

::: {.print-only}
## References
Available upon request
:::



# Formação

#### Superior

**UNIVERSIDADE FEDERAL DO RIO DE JANEIRO** | Rio de Janeiro, RJ

- **Pós-Doutorado Ecologia** | Programa de Pós-Graduação em Ecologia | Março 2016 - Junho 2019
    + Efeito das Mudanças Climáticas sobre as Interações Ecológicas
    + Bolsista PNPD/CAPES  
</br>

- **Ph.D. Ecologia** | Programa de Pós-Graduação em Ecologia | Março 2012 - Fevereiro 2016
    + O efeito de predadores na estrutura e funcionamento de cadeias traficas e sua interação com as mudanças climáticas
    + Bolsista CAPES
    + Prêmio de Melhor Tese de Doutorado defendida no Programa em 2016  
</br>

- **M.Sc. Ecologia** | Programa de Pós-Graduação em Ecologia | Agosto 2009 - Outubro 2011
    + Estruturação da comunidade de macroinvertebrados aquáticos em bromélias-tanque
    + Bolsista CAPES  
</br>

- **B.Sc. Ciências Biológicas** | Especialização em Ecologia | Agosto 2005 - Julho 2009
    + Bromélias como ilhas: Influência das características do habitat sobre a riqueza de macroinvertebrados aquáticos
    + Bolsista FAPERJ  
</br>

#### Complementar

- **DATACAMP**
    + Data Scientist: Customer Channel/Marketing (Basic, Intermediate & Advanced) | 2021
    + Data Scientist: Risk (Basic) | 2021
    + Interactive Data Visualization with R | 2020
    + Unsupervised Machine Learning with R | 2020
    + Supervised Machine Learning with R | 2020
    + Machine Learning Specialist with R | 2020
    + Machine Learning Fundamentals with R | 2020
    + Python Programmer | 2019
    + Data Scientist with Python | 2019
    + Data Analyst with Python | 2019
    + Shiny Fundamentals with R | 2019  
</br>
- **DATA SCIENCE ACADEMY**
    + Formação Inteligência Artificial | Em andamento
    + Python Fundamentos para a Análise de Dados | 2020
    + Microsoft Power BI para Data Science | 2020
    + Big Data Fundamentos | 2020
    + Introdução à Inteligência Artificial | 2020
    + Web Scrapping e Análise de Dados | 2020
    + Soft Skills: Desenvolvendo Suas Habilidades Comportamentais | 2020  
</br>
- **CURSO-R**
    + Dashboards | 2021
    + Web Scrapping | 2021
    + Deploy | 2021
    + Relatórios e Visualização de Dados | 2021
    + Deep Learning | 2020  
</br>
- **COURSERA**
    + Data Science | Johns Hopkins University | Em andamento
        + Reproducible Research | 2021
        + Exploratory Data Analysis | 2021
        + Getting and Cleaning Data | 2021
        + R Programming | 2021
        + The Data Scientist's Toolbox | 2021
    + NLP Specialization | Em andamento
        + Natural Language Processing with Sequence Models | Em andamento
        + Natural Language Processing with Probabilistic Models | 2022
        + Natural Language Processing with Classification and Vector Spaces | 2022
    + Deep Learning Specialization | 2022
        + Sequence Models | 2022
        + Convolutional Neural Networks | 2022
        + Structuring Machine Learning Projects | 2022
        + Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization | 2022
        + Neural Networks and Deep Learning | 2022
    + Introduction to Mathematical Thinking | 2021
    + Learn to Program: Crafting Quality Code | 2021
    + Mathematics for Machine Learning 
        + Principal Component Analysis | 2022
        + Multivariate Calculus | 2021
        + Linear Algebra | 2021  
- **CLOUD**
    + AWS Cloud Practitioner | 2022
  
# Experiência

- **Accenture** | Cientista de Dados | Julho 2019 - Presente
    + Data Science Principal | Abril 2021 - Atual
    + Data Science Manager | Janeiro 2021 - Março 2021
    + Data Science Consultant | Julho 2019 - Dezembro 2020  
</br>

- **Programa de Pós-Graduação em Ecologia/UNICAMP** | Professor Colaborador | Q1 2019
    +  Introdução ao Manejo e Visualizacao de Dados  
</br>

- **Programa de Pós-Graduação em Ecologia/UFRJ** | Professor Colaborador | Março 2016 - Junho 2019
    + Manejo, Visulizacao e Compartilhamento de Dados | 2018  
    + Revisão Sistemática e Meta-Análise | 2016 - 2019
    + Delineamento Experimental e Estatística | 2016 - 2019
    + Introdução à Linguagem R | 2016 - 2019  
</br>

- **Laboratório de Limnologia/UFRJ** | Pesquisador | Maio 2005 - Junho 2019
    + Programa de Monitoramento Integrado dos Igarapés da FLONA Saracá-Taquera | 2009 - 2020
    + Programa de Monitoramento das Lagoas do Norte Fluminense - ECOLagoas | 2005 - 2009